on: push
jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Install pylint
          run: sudo apt update && sudo apt install pylint
        - name: Linting
          run: pylint *.py
    unit_testing:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Unit testing
          run: python3 test.py
    create_package:
        needs: [linting, unit_testing]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Install rpm for ubuntu
          run: sudo apt update && sudo apt install rpm -y
        - name: Rename python script
          run: mv hello_world.py hello_world
        - name: Create a rpm package
          run:  rpmbuild -ba --build-in-place --define "_topdir $(pwd)/rpm" hello_world.spec
        - name: Check package
          run: ls -la rpm/RPMS/noarch
        - uses: actions/upload-artifact@v3
          with:
            name: hello_world.rpm
            path: rpm/RPMS/noarch/hello_world-1.0-1.noarch.rpm
